package br.gov.se.seplag.protocoloatendimento;

import br.gov.se.seplag.commons.v1.CabecalhoSeplag;
import br.gov.se.seplag.commons.v1.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://osb02.itconsulting.com.br:8011/V1/ProtocoloAtendimento?WSDL",
  targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
  name="ProtocoloAtendimento")
@XmlSeeAlso(
  { ObjectFactory.class, br.gov.se.seplag.ebo.v1.ObjectFactory.class, br.gov.se.seplag.protocoloatendimento.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface ProtocoloAtendimento
{
  @WebMethod(operationName="EmitirProtocoloAtendimento", action="http://www.seplag.se.gov.br/ProtocoloAtendimento/EmitirProtocoloAtendimento")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.seplag.se.gov.br/ProtocoloAtendimento/EmitirProtocoloAtendimento", fault =
      { @FaultAction(value="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/EmitirProtocoloAtendimento/Fault/erroInfo",
          className = ErroInfoMessage.class) }, output="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/EmitirProtocoloAtendimentoResponse")
  @WebResult(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
    partName="parameters", name="ResultadoEmitirProtocoloAtendimento")
  public ResultadoEmitirProtocoloAtendimento emitirProtocoloAtendimento(@WebParam(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
      partName="parameters", name="ParametroEmitirProtocoloAtendimento")
    ParametroEmitirProtocoloAtendimento parameters,
    @WebParam(targetNamespace="http://www.seplag.se.gov.br/commons/v1",
      partName="cabecalho", name="cabecalhoSeplag", header=true)
    CabecalhoSeplag cabecalho)
    throws ErroInfoMessage;

  @WebMethod(operationName="AtualizarProtocoloAtendimento", action="http://www.seplag.se.gov.br/ProtocoloAtendimento/AtualizarProtocoloAtendimento")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.seplag.se.gov.br/ProtocoloAtendimento/AtualizarProtocoloAtendimento", fault =
      { @FaultAction(value="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/AtualizarProtocoloAtendimento/Fault/erroInfo",
          className = ErroInfoMessage.class) }, output="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/AtualizarProtocoloAtendimentoResponse")
  @WebResult(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
    partName="parameters", name="ResultadoAtualizarProtocoloAtendimento")
  public ResultadoAtualizarProtocoloAtendimento atualizarProtocoloAtendimento(@WebParam(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
      partName="parameters", name="ParametroAtualizarProtocoloAtendimento")
    ParametroAtualizarProtocoloAtendimento parameters,
    @WebParam(targetNamespace="http://www.seplag.se.gov.br/commons/v1",
      partName="cabecalho", name="cabecalhoSeplag", header=true)
    CabecalhoSeplag cabecalho)
    throws ErroInfoMessage;

  @WebMethod(operationName="ObterProtocoloAtendimento", action="http://www.seplag.se.gov.br/ProtocoloAtendimento/ObterProtocoloAtendimento")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.seplag.se.gov.br/ProtocoloAtendimento/ObterProtocoloAtendimento", fault =
      { @FaultAction(value="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/ObterProtocoloAtendimento/Fault/erroInfo",
          className = ErroInfoMessage.class) }, output="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/ObterProtocoloAtendimentoResponse")
  @WebResult(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
    partName="parameters", name="ResultadoObterProtocoloAtendimento")
  public ResultadoObterProtocoloAtendimento obterProtocoloAtendimento(@WebParam(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
      partName="parameters", name="ParametroObterProtocoloAtendimento")
    ParametroObterProtocoloAtendimento parameters,
    @WebParam(targetNamespace="http://www.seplag.se.gov.br/commons/v1",
      partName="cabecalho", name="cabecalhoSeplag", header=true)
    CabecalhoSeplag cabecalho)
    throws ErroInfoMessage;

  @WebMethod(operationName="GerarCodigoProtocoloAtendimento", action="http://www.seplag.se.gov.br/ProtocoloAtendimento/GerarCodigoProtocoloAtendimento")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.seplag.se.gov.br/ProtocoloAtendimento/GerarCodigoProtocoloAtendimento", fault =
      { @FaultAction(value="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/GerarCodigoProtocoloAtendimento/Fault/erroInfo",
          className = ErroInfoMessage.class) }, output="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/GerarCodigoProtocoloAtendimentoResponse")
  @WebResult(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
    partName="parameters", name="ResultadoGerarCodigoProtocoloAtendimento")
  public ResultadoGerarCodigoProtocoloAtendimento gerarCodigoProtocoloAtendimento(@WebParam(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
      partName="parameters", name="ParametroGerarCodigoProtocoloAtendimento")
    ParametroGerarCodigoProtocoloAtendimento parameters,
    @WebParam(targetNamespace="http://www.seplag.se.gov.br/commons/v1",
      partName="cabecalho", name="cabecalhoSeplag", header=true)
    CabecalhoSeplag cabecalho)
    throws ErroInfoMessage;

  @WebMethod(operationName="ConsultarProtocoloAtendimento", action="http://www.seplag.se.gov.br/ProtocoloAtendimento/GerarCodigoProtocoloAtendimento")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.seplag.se.gov.br/ProtocoloAtendimento/GerarCodigoProtocoloAtendimento", fault =
      { @FaultAction(value="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/ConsultarProtocoloAtendimento/Fault/erroInfo",
          className = ErroInfoMessage.class) }, output="http://www.seplag.se.gov.br/ProtocoloAtendimento/ProtocoloAtendimento/ConsultarProtocoloAtendimentoResponse")
  @WebResult(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
    partName="parameters", name="ResultadoConsultarProtocoloAtendimento")
  public ResultadoConsultarProtocoloAtendimento consultarProtocoloAtendimento(@WebParam(targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
      partName="parameters", name="ParametroConsultarProtocoloAtendimento")
    ParametroConsultarProtocoloAtendimento parameters,
    @WebParam(targetNamespace="http://www.seplag.se.gov.br/commons/v1",
      partName="cabecalho", name="cabecalhoSeplag", header=true)
    CabecalhoSeplag cabecalho)
    throws ErroInfoMessage;
}
