package br.gov.se.seplag.protocoloatendimento;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://osb02.itconsulting.com.br:8011/V1/ProtocoloAtendimento?WSDL",
  targetNamespace="http://www.seplag.se.gov.br/ProtocoloAtendimento",
  name="ProtocoloAtendimento")
@HandlerChain(file="ProtocoloAtendimentoProxy-HandlerChain.xml")
public class ProtocoloAtendimento_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("br.gov.se.seplag.protocoloatendimento.ProtocoloAtendimento_Service");
      URL baseUrl = ProtocoloAtendimento_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ProtocoloAtendimento_Service.class.getResource("http://osb02.itconsulting.com.br:8011/V1/ProtocoloAtendimento?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://osb02.itconsulting.com.br:8011/V1/ProtocoloAtendimento?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://osb02.itconsulting.com.br:8011/V1/ProtocoloAtendimento?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://osb02.itconsulting.com.br:8011/V1/ProtocoloAtendimento?WSDL",
          e);
    }
  }

  public ProtocoloAtendimento_Service()
  {
    super(wsdlLocationURL,
          new QName("http://www.seplag.se.gov.br/ProtocoloAtendimento",
                    "ProtocoloAtendimento"));
  }

  public ProtocoloAtendimento_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ProtocoloAtendimentoSOAP")
  public ProtocoloAtendimento getProtocoloAtendimentoSOAP()
  {
    return (ProtocoloAtendimento) super.getPort(new QName("http://www.seplag.se.gov.br/ProtocoloAtendimento",
                                                          "ProtocoloAtendimentoSOAP"),
                                                ProtocoloAtendimento.class);
  }

  @WebEndpoint(name="ProtocoloAtendimentoSOAP")
  public ProtocoloAtendimento getProtocoloAtendimentoSOAP(WebServiceFeature... features)
  {
    return (ProtocoloAtendimento) super.getPort(new QName("http://www.seplag.se.gov.br/ProtocoloAtendimento",
                                                          "ProtocoloAtendimentoSOAP"),
                                                ProtocoloAtendimento.class,
                                                features);
  }
}
