package br.gov.se.seplag.senhaatendimento;

import br.gov.se.seplag.RequestFixo;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation=RequestFixo.WSDL_LOCATION + "V1/SenhaAtendimento?wsdl",
  targetNamespace="http://www.seplag.se.gov.br/SenhaAtendimento", name="SenhaAtendimento")
@HandlerChain(file="SenhaAtendimentoProxy-HandlerChain.xml")
public class SenhaAtendimento_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("br.gov.se.seplag.senhaatendimento.SenhaAtendimento_Service");
      URL baseUrl = SenhaAtendimento_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            SenhaAtendimento_Service.class.getResource(RequestFixo.WSDL_LOCATION + "V1/SenhaAtendimento?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/SenhaAtendimento?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/SenhaAtendimento?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://osb.itconsulting.com.br:8011/V1/SenhaAtendimento?wsdl",
          e);
    }
  }

  public SenhaAtendimento_Service()
  {
    super(wsdlLocationURL,
          new QName("http://www.seplag.se.gov.br/SenhaAtendimento",
                    "SenhaAtendimento"));
  }

  public SenhaAtendimento_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="SenhaAtendimentoSOAP")
  public SenhaAtendimento getSenhaAtendimentoSOAP()
  {
    return (SenhaAtendimento) super.getPort(new QName("http://www.seplag.se.gov.br/SenhaAtendimento",
                                                      "SenhaAtendimentoSOAP"),
                                            SenhaAtendimento.class);
  }

  @WebEndpoint(name="SenhaAtendimentoSOAP")
  public SenhaAtendimento getSenhaAtendimentoSOAP(WebServiceFeature... features)
  {
    return (SenhaAtendimento) super.getPort(new QName("http://www.seplag.se.gov.br/SenhaAtendimento",
                                                      "SenhaAtendimentoSOAP"),
                                            SenhaAtendimento.class,
                                            features);
  }
}
