package br.gov.se.seplag.cicsergipe;

import br.gov.se.seplag.RequestFixo;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation=RequestFixo.WSDL_LOCATION + "V1/CICSergipe?wsdl",
  targetNamespace="http://www.seplag.se.gov.br/CICSergipe", name="CICSergipe")
@HandlerChain(file="CICSergipeProxy-HandlerChain.xml")
public class CICSergipe
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("br.gov.se.seplag.cicsergipe.CICSergipe");
      URL baseUrl = CICSergipe.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            CICSergipe.class.getResource(RequestFixo.WSDL_LOCATION + "V1/CICSergipe?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/CICSergipe?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/CICSergipe?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://osb.itconsulting.com.br:8011/V1/CICSergipe?wsdl",
          e);
    }
  }

  public CICSergipe()
  {
    super(wsdlLocationURL,
          new QName("http://www.seplag.se.gov.br/CICSergipe",
                    "CICSergipe"));
  }

  public CICSergipe(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="CICSergipeSOAP_Port")
  public CICSergipe_PortType getCICSergipeSOAP_Port()
  {
    return (CICSergipe_PortType) super.getPort(new QName("http://www.seplag.se.gov.br/CICSergipe",
                                                         "CICSergipeSOAP_Port"),
                                               CICSergipe_PortType.class);
  }

  @WebEndpoint(name="CICSergipeSOAP_Port")
  public CICSergipe_PortType getCICSergipeSOAP_Port(WebServiceFeature... features)
  {
    return (CICSergipe_PortType) super.getPort(new QName("http://www.seplag.se.gov.br/CICSergipe",
                                                         "CICSergipeSOAP_Port"),
                                               CICSergipe_PortType.class,
                                               features);
  }
}
