package br.gov.se.seplag.correioscep;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://osb02.itconsulting.com.br:8011/V1/CorreiosCEP?WSDL",
  targetNamespace="http://www.seplag.se.gov.br/CorreiosCEP", name="CorreiosCEP")
@HandlerChain(file="CorreiosCEPProxy-HandlerChain.xml")
public class CorreiosCEP
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("br.gov.se.seplag.correioscep.CorreiosCEP");
      URL baseUrl = CorreiosCEP.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            CorreiosCEP.class.getResource("http://osb02.itconsulting.com.br:8011/V1/CorreiosCEP?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://osb02.itconsulting.com.br:8011/V1/CorreiosCEP?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://osb02.itconsulting.com.br:8011/V1/CorreiosCEP?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://osb02.itconsulting.com.br:8011/V1/CorreiosCEP?WSDL",
          e);
    }
  }

  public CorreiosCEP()
  {
    super(wsdlLocationURL,
          new QName("http://www.seplag.se.gov.br/CorreiosCEP",
                    "CorreiosCEP"));
  }

  public CorreiosCEP(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="CorreiosCEPSOAP_Port")
  public br.gov.se.seplag.correioscep.CorreiosCEP_PortType getCorreiosCEPSOAP_Port()
  {
    return (br.gov.se.seplag.correioscep.CorreiosCEP_PortType) super.getPort(new QName("http://www.seplag.se.gov.br/CorreiosCEP",
                                                                                       "CorreiosCEPSOAP_Port"),
                                                                             br.gov.se.seplag.correioscep.CorreiosCEP_PortType.class);
  }

  @WebEndpoint(name="CorreiosCEPSOAP_Port")
  public br.gov.se.seplag.correioscep.CorreiosCEP_PortType getCorreiosCEPSOAP_Port(WebServiceFeature... features)
  {
    return (br.gov.se.seplag.correioscep.CorreiosCEP_PortType) super.getPort(new QName("http://www.seplag.se.gov.br/CorreiosCEP",
                                                                                       "CorreiosCEPSOAP_Port"),
                                                                             br.gov.se.seplag.correioscep.CorreiosCEP_PortType.class,
                                                                             features);
  }
}
