package br.gov.se.seplag.docsprocsnecessariosatendimento;

import br.gov.se.seplag.RequestFixo;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation=RequestFixo.WSDL_LOCATION + "V1/DocsProcsNecessariosAtendimento?wsdl",
  targetNamespace="http://www.seplag.se.gov.br/DocsProcsNecessariosAtendimento",
  name="DocsProcsNecessariosAtendimento")
@HandlerChain(file="DocsProcsNecessariosAtendimentoProxy-HandlerChain.xml")
public class DocsProcsNecessariosAtendimento_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("br.gov.se.seplag.docsprocsnecessariosatendimento.DocsProcsNecessariosAtendimento_Service");
      URL baseUrl =
        DocsProcsNecessariosAtendimento_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            DocsProcsNecessariosAtendimento_Service.class.getResource(RequestFixo.WSDL_LOCATION + "V1/DocsProcsNecessariosAtendimento?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/DocsProcsNecessariosAtendimento?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/DocsProcsNecessariosAtendimento?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://osb.itconsulting.com.br:8011/V1/DocsProcsNecessariosAtendimento?wsdl",
          e);
    }
  }

  public DocsProcsNecessariosAtendimento_Service()
  {
    super(wsdlLocationURL,
          new QName("http://www.seplag.se.gov.br/DocsProcsNecessariosAtendimento",
                    "DocsProcsNecessariosAtendimento"));
  }

  public DocsProcsNecessariosAtendimento_Service(URL wsdlLocation,
                                                 QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="DocsProcsNecessariosAtendimentoSOAP")
  public DocsProcsNecessariosAtendimento getDocsProcsNecessariosAtendimentoSOAP()
  {
    return (DocsProcsNecessariosAtendimento) super.getPort(new QName("http://www.seplag.se.gov.br/DocsProcsNecessariosAtendimento",
                                                                     "DocsProcsNecessariosAtendimentoSOAP"),
                                                           DocsProcsNecessariosAtendimento.class);
  }

  @WebEndpoint(name="DocsProcsNecessariosAtendimentoSOAP")
  public DocsProcsNecessariosAtendimento getDocsProcsNecessariosAtendimentoSOAP(WebServiceFeature... features)
  {
    return (DocsProcsNecessariosAtendimento) super.getPort(new QName("http://www.seplag.se.gov.br/DocsProcsNecessariosAtendimento",
                                                                     "DocsProcsNecessariosAtendimentoSOAP"),
                                                           DocsProcsNecessariosAtendimento.class,
                                                           features);
  }
}
