package br.gov.se.seplag.agendamentoatendimento;

import br.gov.se.seplag.RequestFixo;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation=RequestFixo.WSDL_LOCATION + "V1/AgendamentoAtendimento?wsdl",
  targetNamespace="http://www.seplag.se.gov.br/AgendamentoAtendimento",
  name="AgendamentoAtendimento")
@HandlerChain(file="AgendamentoAtendimentoProxy-HandlerChain.xml")
public class AgendamentoAtendimento
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("br.gov.se.seplag.agendamentoatendimento.AgendamentoAtendimento");
      URL baseUrl = AgendamentoAtendimento.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            AgendamentoAtendimento.class.getResource(RequestFixo.WSDL_LOCATION + "V1/AgendamentoAtendimento?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/AgendamentoAtendimento?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/AgendamentoAtendimento?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using " + RequestFixo.WSDL_LOCATION + "V1/AgendamentoAtendimento?wsdl",
          e);
    }
  }

  public AgendamentoAtendimento()
  {
    super(wsdlLocationURL,
          new QName("http://www.seplag.se.gov.br/AgendamentoAtendimento",
                    "AgendamentoAtendimento"));
  }

  public AgendamentoAtendimento(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="AgendamentoAtendimentoSOAP_Port")
  public AgendamentoAtendimento_PortType getAgendamentoAtendimentoSOAP_Port()
  {
    return (AgendamentoAtendimento_PortType) super.getPort(new QName("http://www.seplag.se.gov.br/AgendamentoAtendimento",
                                                                     "AgendamentoAtendimentoSOAP_Port"),
                                                           AgendamentoAtendimento_PortType.class);
  }

  @WebEndpoint(name="AgendamentoAtendimentoSOAP_Port")
  public AgendamentoAtendimento_PortType getAgendamentoAtendimentoSOAP_Port(WebServiceFeature... features)
  {
    return (AgendamentoAtendimento_PortType) super.getPort(new QName("http://www.seplag.se.gov.br/AgendamentoAtendimento",
                                                                     "AgendamentoAtendimentoSOAP_Port"),
                                                           AgendamentoAtendimento_PortType.class,
                                                           features);
  }
}
