package br.gov.se.seplag.servicoatendimento;

import br.gov.se.seplag.RequestFixo;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation=RequestFixo.WSDL_LOCATION + "V1/ServicoAtendimento?wsdl",
  targetNamespace="http://www.seplag.se.gov.br/ServicoAtendimento", name="ServicoAtendimento")
@HandlerChain(file="ServicoAtendimentoProxy-HandlerChain.xml")
public class ServicoAtendimento_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("br.gov.se.seplag.servicoatendimento.ServicoAtendimento_Service");
      URL baseUrl = ServicoAtendimento_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ServicoAtendimento_Service.class.getResource(RequestFixo.WSDL_LOCATION + "V1/ServicoAtendimento?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/ServicoAtendimento?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, RequestFixo.WSDL_LOCATION + "V1/ServicoAtendimento?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using " + RequestFixo.WSDL_LOCATION + "V1/ServicoAtendimento?wsdl",
          e);
    }
  }

  public ServicoAtendimento_Service()
  {
    super(wsdlLocationURL,
          new QName("http://www.seplag.se.gov.br/ServicoAtendimento",
                    "ServicoAtendimento"));
  }

  public ServicoAtendimento_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ServicoAtendimentoSOAP")
  public ServicoAtendimento getServicoAtendimentoSOAP()
  {
    return (ServicoAtendimento) super.getPort(new QName("http://www.seplag.se.gov.br/ServicoAtendimento",
                                                        "ServicoAtendimentoSOAP"),
                                              ServicoAtendimento.class);
  }

  @WebEndpoint(name="ServicoAtendimentoSOAP")
  public ServicoAtendimento getServicoAtendimentoSOAP(WebServiceFeature... features)
  {
    return (ServicoAtendimento) super.getPort(new QName("http://www.seplag.se.gov.br/ServicoAtendimento",
                                                        "ServicoAtendimentoSOAP"),
                                              ServicoAtendimento.class,
                                              features);
  }
}
