package br.gov.se.seplag.anexoprocessosatendimento;

import br.gov.se.seplag.RequestFixo;
import br.gov.se.seplag.commons.v1.CabecalhoSeplag;
import br.gov.se.seplag.commons.v1.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation=RequestFixo.WSDL_LOCATION + "V1/AnexoProcessosAtendimento?wsdl",
  targetNamespace="http://www.seplag.se.gov.br/AnexoProcessosAtendimento",
  name="AnexoProcessosAtendimento")
@XmlSeeAlso(
  { ObjectFactory.class, br.gov.se.seplag.ebo.v1.ObjectFactory.class, br.gov.se.seplag.anexoprocessosatendimento.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface AnexoProcessosAtendimento
{
  @WebMethod(operationName="IncluirPorAtendimento", action="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/IncluirPorAtendimento")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/IncluirPorAtendimento", fault =
      { @FaultAction(value="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/AnexoProcessosAtendimento/IncluirPorAtendimento/Fault/erroInfo",
          className = ErroInfoMessage.class) }, output="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/AnexoProcessosAtendimento/IncluirPorAtendimentoResponse")
  @WebResult(targetNamespace="http://www.seplag.se.gov.br/AnexoProcessosAtendimento",
    partName="parameters", name="ResultadoIncluirPorAtendimento")
  public ResultadoIncluirPorAtendimento incluirPorAtendimento(@WebParam(targetNamespace="http://www.seplag.se.gov.br/AnexoProcessosAtendimento",
      partName="parameters", name="ParametroIncluirPorAtendimento")
    ParametroIncluirPorAtendimento parameters, @WebParam(targetNamespace="http://www.seplag.se.gov.br/commons/v1",
      partName="Cabecalho", name="cabecalhoSeplag", header=true)
    CabecalhoSeplag Cabecalho)
    throws ErroInfoMessage;

  @WebMethod(operationName="ListarAnexosValidos", action="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/ListarAnexosValidos")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/ListarAnexosValidos", fault =
      { @FaultAction(value="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/AnexoProcessosAtendimento/ListarAnexosValidos/Fault/erroInfo",
          className = ErroInfoMessage.class) }, output="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/AnexoProcessosAtendimento/ListarAnexosValidosResponse")
  @WebResult(targetNamespace="http://www.seplag.se.gov.br/AnexoProcessosAtendimento",
    partName="parameters", name="ResultadoListarAnexosValidos")
  public ResultadoListarAnexosValidos listarAnexosValidos(@WebParam(targetNamespace="http://www.seplag.se.gov.br/AnexoProcessosAtendimento",
      partName="parameters", name="ParametroListarAnexosValidos")
    ParametroListarAnexosValidos parameters, @WebParam(targetNamespace="http://www.seplag.se.gov.br/commons/v1",
      partName="Cabecalho", name="cabecalhoSeplag", header=true)
    CabecalhoSeplag Cabecalho)
    throws ErroInfoMessage;

  @WebMethod(operationName="ListarPorAtendimento", action="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/ListarPorAtendimento")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/ListarPorAtendimento", fault =
      { @FaultAction(value="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/AnexoProcessosAtendimento/ListarPorAtendimento/Fault/erroInfo",
          className = ErroInfoMessage.class) }, output="http://www.seplag.se.gov.br/AnexoProcessosAtendimento/AnexoProcessosAtendimento/ListarPorAtendimentoResponse")
  @WebResult(targetNamespace="http://www.seplag.se.gov.br/AnexoProcessosAtendimento",
    partName="parameters", name="ResultadoListarPorAtendimento")
  public ResultadoListarPorAtendimento listarPorAtendimento(@WebParam(targetNamespace="http://www.seplag.se.gov.br/AnexoProcessosAtendimento",
      partName="parameters", name="ParametroListarPorAtendimento")
    ParametroListarPorAtendimento parameters, @WebParam(targetNamespace="http://www.seplag.se.gov.br/commons/v1",
      partName="Cabecalho", name="cabecalhoSeplag", header=true)
    CabecalhoSeplag Cabecalho)
    throws ErroInfoMessage;
}
